# Generated by Django 4.2.7 on 2025-12-06 07:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0002_bus_booking_calculated_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='bus_number',
            field=models.CharField(blank=True, help_text='Actual bus registration number', max_length=20),
        ),
        migrations.AddField(
            model_name='booking',
            name='departure_time',
            field=models.TimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='sms_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp_sent',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='booking',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(blank=True, help_text='Seat number (1-42)', null=True),
        ),
    ]
