# Generated by Django 4.2.7 on 2025-12-06 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0003_booking_bus_number_booking_departure_time_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='bus_number',
            field=models.CharField(blank=True, default='', help_text='Actual bus registration number', max_length=20),
        ),
        migrations.AlterField(
            model_name='booking',
            name='departure_time',
            field=models.TimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.IntegerField(blank=True, default=None, help_text='Seat number (1-42)', null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sms_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='sms_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
        migrations.AlterField(
            model_name='booking',
            name='whatsapp_sent',
            field=models.BooleanField(blank=True, default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='whatsapp_sent_at',
            field=models.DateTimeField(blank=True, default=None, null=True),
        ),
    ]
