# Generated by Django 4.2.7 on 2025-12-06 07:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0004_alter_booking_bus_number_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='booking',
            name='seat_number',
            field=models.CharField(blank=True, default='', help_text='Seat number (1-42)', max_length=10),
        ),
    ]
