# Generated by Django 4.2.7 on 2025-12-14 13:31

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0006_alter_booking_seat_number_alter_bus_capacity'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, help_text='Volunteer responsible for this passenger', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='bus',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, help_text='Volunteer responsible for this bus', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='payment',
            name='payment_received_date',
            field=models.DateField(blank=True, help_text='Actual date when payment was received', null=True),
        ),
        migrations.AddField(
            model_name='payment',
            name='updated_at',
            field=models.DateTimeField(auto_now=True),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_date',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.CreateModel(
            name='SeatCancellation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('cancellation_date', models.DateTimeField(auto_now_add=True)),
                ('reason', models.CharField(choices=[('Passenger Request', 'Passenger Request'), ('Medical Emergency', 'Medical Emergency'), ('Travel Plan Changed', 'Travel Plan Changed'), ('Other', 'Other')], default='Passenger Request', max_length=50)),
                ('refund_amount', models.DecimalField(decimal_places=2, default=0, help_text='Amount to be refunded', max_digits=10)),
                ('refund_processed', models.BooleanField(default=False)),
                ('refund_date', models.DateField(blank=True, null=True)),
                ('notes', models.TextField(blank=True)),
                ('original_seat_number', models.CharField(blank=True, max_length=10)),
                ('original_bus_number', models.CharField(blank=True, max_length=20)),
                ('original_amount_paid', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('booking', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='cancellations', to='bookings.booking')),
                ('cancelled_by', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
