# Generated by Django 4.2.7 on 2025-12-14 13:33

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0007_booking_assigned_volunteer_bus_assigned_volunteer_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='allow_unpaid_allocation',
            field=models.BooleanField(default=False, help_text='Allow seat allocation even if payment is pending'),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_updated_at',
            field=models.DateTimeField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='amount_updated_by',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='amount_updates', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddField(
            model_name='booking',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, help_text='Custom booking amount (overrides calculated price)', max_digits=10, null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='payment_status',
            field=models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending'), ('Partial', 'Partial')], default='Pending', max_length=20),
        ),
    ]
