# Generated by Django 4.2.7 on 2025-12-23 04:20

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('bookings', '0008_booking_allow_unpaid_allocation_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='booking',
            old_name='calculated_price',
            new_name='onward_price',
        ),
        migrations.RenameField(
            model_name='seatcancellation',
            old_name='original_seat_number',
            new_name='original_onward_seat',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_updated_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='amount_updated_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='assigned_bus',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='bus_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='data_captured_by',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='data_captured_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='departure_time',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='onwards_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='return_date',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='seat_number',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sms_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='sms_sent_at',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='whatsapp_sent',
        ),
        migrations.RemoveField(
            model_name='booking',
            name='whatsapp_sent_at',
        ),
        migrations.RemoveField(
            model_name='seatcancellation',
            name='original_bus_number',
        ),
        migrations.AddField(
            model_name='booking',
            name='journey_type',
            field=models.CharField(choices=[('ONWARD', 'Onward Only'), ('RETURN', 'Return Only'), ('BOTH', 'Both Journeys')], default='BOTH', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='onward_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onward_bookings', to='bookings.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='onward_seat_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_bus',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='bookings.bus'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_seat_number',
            field=models.CharField(blank=True, default='', max_length=10),
        ),
        migrations.AddField(
            model_name='booking',
            name='total_price',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name='seatcancellation',
            name='journey_type',
            field=models.CharField(blank=True, choices=[('ONWARD', 'Onward'), ('RETURN', 'Return'), ('BOTH', 'Both')], max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='seatcancellation',
            name='original_return_seat',
            field=models.CharField(blank=True, max_length=10),
        ),
        migrations.AlterField(
            model_name='booking',
            name='allow_unpaid_allocation',
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name='booking',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_bookings', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='booking',
            name='custom_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=10, null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='assigned_volunteer',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='assigned_buses', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=42),
        ),
        migrations.AlterField(
            model_name='payment',
            name='payment_received_date',
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='seatcancellation',
            name='refund_amount',
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.CreateModel(
            name='JourneyPricing',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('ONWARD', 'Onward Journey'), ('RETURN', 'Return Journey')], max_length=10)),
                ('age_criteria', models.CharField(choices=[('M-12 & Below', 'M-12 & Below'), ('F-12 & Below', 'F-12 & Below'), ('M-65 & Above', 'M-65 & Above'), ('F-Above 12 & Below 75', 'F-Above 12 & Below 75'), ('M&F-75 & Above', 'M&F-75 & Above'), ('M-Above 12 & Below 65', 'M-Above 12 & Below 65')], max_length=30)),
                ('amount', models.DecimalField(decimal_places=2, max_digits=10)),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
            ],
            options={
                'unique_together': {('journey_type', 'age_criteria')},
            },
        ),
        migrations.CreateModel(
            name='Journey',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('journey_type', models.CharField(choices=[('ONWARD', 'Onward Journey'), ('RETURN', 'Return Journey')], max_length=10)),
                ('journey_date', models.DateField()),
                ('is_active', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['journey_date', 'journey_type'],
                'unique_together': {('journey_type', 'journey_date')},
            },
        ),
        migrations.AddField(
            model_name='booking',
            name='onward_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='onward_bookings', to='bookings.journey'),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='return_bookings', to='bookings.journey'),
        ),
        migrations.AddField(
            model_name='bus',
            name='journey',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='buses', to='bookings.journey'),
        ),
        migrations.AlterUniqueTogether(
            name='bus',
            unique_together={('bus_number', 'journey')},
        ),
    ]
