# Generated by Django 4.2.7 on 2026-01-13 08:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0009_rename_calculated_price_booking_onward_price_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='booking',
            name='attendance_notes',
            field=models.TextField(blank=True, help_text='Notes for attendance/shifting'),
        ),
        migrations.AddField(
            model_name='booking',
            name='is_volunteer',
            field=models.BooleanField(default=False, help_text='Is this passenger a volunteer?'),
        ),
        migrations.AddField(
            model_name='booking',
            name='onward_attendance',
            field=models.BooleanField(blank=True, default=None, help_text='True=Present, False=Absent, None=Not Marked', null=True),
        ),
        migrations.AddField(
            model_name='booking',
            name='return_attendance',
            field=models.BooleanField(blank=True, default=None, help_text='True=Present, False=Absent, None=Not Marked', null=True),
        ),
        migrations.AlterField(
            model_name='bus',
            name='capacity',
            field=models.IntegerField(default=40),
        ),
    ]
