# Generated by Django 4.2.7 on 2026-01-14 18:19

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('bookings', '0010_booking_attendance_notes_booking_is_volunteer_and_more'),
    ]

    operations = [
        migrations.CreateModel(
            name='OnSpotPassenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('age', models.IntegerField()),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('journey_type', models.CharField(choices=[('ONWARD', 'Onward'), ('RETURN', 'Return')], max_length=10)),
                ('calculated_price', models.DecimalField(decimal_places=2, default=0, max_digits=10)),
                ('payment_status', models.CharField(choices=[('Paid', 'Paid'), ('Pending', 'Pending')], default='Pending', max_length=20)),
                ('attendance', models.BooleanField(default=True, help_text='On-spot passengers are present by default')),
                ('notes', models.TextField(blank=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('bus', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='onspot_passengers', to='bookings.bus')),
            ],
            options={
                'ordering': ['-created_at'],
            },
        ),
    ]
