# Generated by Django 4.2.7 on 2025-12-14 13:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='can_cancel_seats',
            field=models.BooleanField(default=False, help_text='Can cancel seat allocations'),
        ),
        migrations.AddField(
            model_name='user',
            name='can_modify_seat_allocation',
            field=models.BooleanField(default=False, help_text='Can modify seat allocations'),
        ),
    ]
