# Generated by Django 4.2.7 on 2025-12-22 08:25

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('authentication', '0002_user_can_cancel_seats_and_more'),
        ('authentication', '0002_user_groups_permissions'),
    ]

    operations = [
    ]
