# Generated by Django 4.2.7 on 2025-12-04 13:36

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Passenger',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('gender', models.CharField(choices=[('M', 'Male'), ('F', 'Female')], max_length=1)),
                ('age_criteria', models.CharField(choices=[('M-12 & Below', 'Male - 12 & Below'), ('M-Above 12 & Below 65', 'Male - Above 12 & Below 65'), ('M-65 & Above', 'Male - 65 & Above'), ('F-12 & Below', 'Female - 12 & Below'), ('F-Above 12 & Below 75', 'Female - Above 12 & Below 75'), ('M&F-75 & Above', 'Male & Female - 75 & Above')], max_length=50)),
                ('mobile_no', models.CharField(blank=True, max_length=15)),
                ('category', models.CharField(choices=[('Satsang', 'Satsang'), ('Sewadal', 'Sewadal'), ('Bal Sewadal', 'Bal Sewadal')], max_length=20)),
                ('aadhar_received', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name'],
            },
        ),
    ]
