# Generated by Django 4.2.7 on 2025-12-04 15:39

from django.db import migrations, models
import passengers.models
import passengers.validators


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='aadhar_document',
            field=models.FileField(blank=True, help_text='Upload Aadhar card (PDF, JPG, PNG, WEBP - Max 5MB)', null=True, upload_to=passengers.models.passenger_document_path, validators=[passengers.validators.validate_document_file]),
        ),
        migrations.AddField(
            model_name='passenger',
            name='verification_notes',
            field=models.TextField(blank=True, help_text='Volunteer verification notes'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='verification_status',
            field=models.CharField(choices=[('Not Required', 'Not Required'), ('Pending', 'Pending Verification'), ('Verified', 'Verified'), ('Rejected', 'Rejected')], default='Not Required', max_length=20),
        ),
    ]
