# Generated by Django 4.2.7 on 2025-12-06 07:02

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0002_passenger_aadhar_document_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='related_to',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='family_members', to='passengers.passenger'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='relationship',
            field=models.CharField(blank=True, help_text='e.g., Spouse, Child, Parent, Sibling', max_length=50),
        ),
    ]
