# Generated by Django 4.2.7 on 2025-12-23 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('passengers', '0005_passenger_aadhar_number'),
    ]

    operations = [
        migrations.AddField(
            model_name='passenger',
            name='aadhar_required',
            field=models.BooleanField(default=False, help_text='Auto-calculated based on age criteria'),
        ),
        migrations.AddField(
            model_name='passenger',
            name='age',
            field=models.IntegerField(blank=True, help_text='Age in years', null=True),
        ),
    ]
